# Generated by Django 4.0.1 on 2023-11-23 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetig',
            name='KDUNIT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.k_dunit'),
            preserve_default=False,
        ),
    ]
