# Generated by Django 4.0.1 on 2023-12-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_kuris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetig',
            name='KDUNIT',
        ),
        migrations.CreateModel(
            name='KdMembersMeetig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('purpose', models.CharField(max_length=200)),
                ('KDUNIT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.k_dunit')),
            ],
        ),
    ]
