# Generated by Django 4.0.1 on 2023-12-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_meetig_kdunit_kdmembersmeetig'),
    ]

    operations = [
        migrations.AddField(
            model_name='k_dunit',
            name='Email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='k_dunit',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
