# Generated by Django 4.0.1 on 2023-12-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_k_dunit_email_k_dunit_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='KDUNIT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.k_dunit'),
            preserve_default=False,
        ),
    ]
