# Generated by Django 4.0.1 on 2023-12-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_payment_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='KDMEMBER',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='winner',
        ),
        migrations.AddField(
            model_name='payment',
            name='ORDERMAIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.order_main'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Kuri_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('winner', models.CharField(max_length=200)),
                ('KDMEMBER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.k_dmembers')),
                ('KDUNIT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.k_dunit')),
                ('KURIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.kuris')),
            ],
        ),
    ]
